### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by parsaloi**
Pr to merge changes of the ReadMe file

### CODE REVIEW

**Review by KingMaina — APPROVED** [review]
Good start. Remember to update the sections accordingly. Let's aim for good docs as much as good code

**Comment by KingMaina** [comment]
@Parsaloi Review approved but conflicts detected. I am not sure if it's because I just approved the other one and it updated the repo. Maybe try committing again here or explore options you know or git's suggestions

**Comment by parsaloi** [comment]
I think it okay. I see it like the change on the readMe file might be the cause of the conflicts. But I guess the code is okay

**Comment by KingMaina** [comment]
I think its bugged or?

**Comment by KingMaina** [comment]
you can try opening another pr

**Comment by parsaloi** [comment]
- This will keep me hooked @KingMaina
- There is an implementation for orchestrating Kafka resources written in `Python` that is simpler to use
- That could be a project we collaborate on...

**Pull request closed without merging**
